"""Static command-palette catalog mirrored from frontend/data/search-data.tsx."""

from __future__ import annotations

from typing import Any

PAGE_ACTIONS = ["open", "ask-ai"]
ASSET_ACTIONS = [
    "open",
    "analyze",
    "open-chart",
    "paper-trade",
    "live-trade",
    "create-alert",
    "copy-symbol",
    "favorite",
]

SEARCH_CATALOG: list[dict[str, Any]] = [
    {
        "id": "page-dashboard",
        "title": "Dashboard",
        "subtitle": "Overview and live desk",
        "category": "pages",
        "kind": "page",
        "href": "/dashboard",
        "keywords": ["home", "overview", "open dashboard", "go home"],
        "icon": "dashboard",
        "actions": PAGE_ACTIONS,
        "boost": 0.2,
    },
    {
        "id": "page-markets",
        "title": "Markets",
        "subtitle": "Screener and liquidity",
        "category": "pages",
        "kind": "page",
        "href": "/market",
        "keywords": ["market", "go to markets", "screener", "assets"],
        "icon": "market",
        "actions": PAGE_ACTIONS,
        "boost": 0.2,
    },
    {
        "id": "page-ai-analysis",
        "title": "AI Analysis",
        "subtitle": "Chart workspace and signals",
        "category": "ai-analysis",
        "kind": "page",
        "href": "/ai-analysis",
        "keywords": ["analysis", "open btc analysis", "chart", "ai analysis"],
        "icon": "analysis",
        "actions": PAGE_ACTIONS,
        "boost": 0.15,
    },
    {
        "id": "page-ai-chat",
        "title": "AI Chat",
        "subtitle": "Ask AI and run commands",
        "category": "ai-conversations",
        "kind": "page",
        "href": "/ai-chat",
        "keywords": ["ask ai", "open ai chat", "chat", "command center"],
        "icon": "chat",
        "actions": PAGE_ACTIONS,
        "boost": 0.15,
    },
    {
        "id": "page-strategies",
        "title": "Strategies",
        "subtitle": "Builder and backtests",
        "category": "strategies",
        "kind": "page",
        "href": "/strategies",
        "keywords": ["strategy", "create strategy", "builder", "start backtest"],
        "icon": "strategies",
        "actions": PAGE_ACTIONS,
        "boost": 0.1,
    },
    {
        "id": "page-paper",
        "title": "Paper Trading",
        "subtitle": "Simulate trades risk-free",
        "category": "pages",
        "kind": "page",
        "href": "/paper-trading",
        "keywords": ["paper", "open paper trading", "simulate", "practice"],
        "icon": "paper",
        "actions": PAGE_ACTIONS,
        "boost": 0.15,
    },
    {
        "id": "page-live",
        "title": "Live Trading",
        "subtitle": "Execution desk",
        "category": "pages",
        "kind": "page",
        "href": "/live-trading",
        "keywords": ["live", "open live trading", "execute"],
        "icon": "live",
        "actions": PAGE_ACTIONS,
        "boost": 0.15,
    },
    {
        "id": "page-portfolio",
        "title": "Portfolio",
        "subtitle": "Holdings and performance",
        "category": "portfolio",
        "kind": "page",
        "href": "/portfolio",
        "keywords": ["portfolio", "open portfolio", "holdings", "positions"],
        "icon": "portfolio",
        "actions": PAGE_ACTIONS,
        "boost": 0.2,
    },
    {
        "id": "page-journal",
        "title": "Journal",
        "subtitle": "Trade log and review",
        "category": "journal",
        "kind": "page",
        "href": "/journal",
        "keywords": ["journal", "show journal", "trade history"],
        "icon": "journal",
        "actions": PAGE_ACTIONS,
        "boost": 0.15,
    },
    {
        "id": "page-alerts",
        "title": "Alerts",
        "subtitle": "Price and AI monitors",
        "category": "alerts",
        "kind": "page",
        "href": "/alerts",
        "keywords": ["alerts", "go to alerts", "create alert", "notify"],
        "icon": "alerts",
        "actions": PAGE_ACTIONS,
        "boost": 0.15,
    },
    {
        "id": "page-settings",
        "title": "Settings",
        "subtitle": "Profile, API, risk",
        "category": "settings",
        "kind": "page",
        "href": "/settings",
        "keywords": ["settings", "open settings", "preferences", "api keys", "risk"],
        "icon": "settings",
        "actions": PAGE_ACTIONS,
        "boost": 0.1,
    },
    {
        "id": "asset-btc",
        "title": "BTC/USDT",
        "subtitle": "Bitcoin · Markets",
        "category": "trading-pairs",
        "kind": "pair",
        "href": "/market",
        "symbol": "BTCUSDT",
        "keywords": ["btc", "bitcoin", "btc/usdt"],
        "icon": "asset",
        "actions": ASSET_ACTIONS,
        "boost": 0.35,
    },
    {
        "id": "asset-eth",
        "title": "ETH/USDT",
        "subtitle": "Ethereum · Markets",
        "category": "trading-pairs",
        "kind": "pair",
        "href": "/market",
        "symbol": "ETHUSDT",
        "keywords": ["eth", "ethereum", "analyze eth"],
        "icon": "asset",
        "actions": ASSET_ACTIONS,
        "boost": 0.3,
    },
    {
        "id": "asset-sol",
        "title": "SOL/USDT",
        "subtitle": "Solana · Markets",
        "category": "trading-pairs",
        "kind": "pair",
        "href": "/market",
        "symbol": "SOLUSDT",
        "keywords": ["sol", "solana"],
        "icon": "asset",
        "actions": ASSET_ACTIONS,
        "boost": 0.25,
    },
    {
        "id": "asset-link",
        "title": "LINK/USDT",
        "subtitle": "Chainlink · Markets",
        "category": "trading-pairs",
        "kind": "pair",
        "href": "/market",
        "symbol": "LINKUSDT",
        "keywords": ["link", "chainlink"],
        "icon": "asset",
        "actions": ASSET_ACTIONS,
        "boost": 0.1,
    },
    {
        "id": "cmd-analyze-btc",
        "title": "Analyze BTC",
        "subtitle": "Open AI Analysis for Bitcoin",
        "category": "commands",
        "kind": "command",
        "href": "/ai-analysis",
        "symbol": "BTCUSDT",
        "keywords": ["open btc analysis", "analyze btc", "btc analysis"],
        "icon": "command",
        "actions": ["open", "ask-ai"],
        "is_command": True,
        "boost": 0.25,
    },
    {
        "id": "cmd-create-alert",
        "title": "Create Alert",
        "subtitle": "Open alerts workspace",
        "category": "commands",
        "kind": "command",
        "href": "/alerts",
        "keywords": ["create alert", "new alert", "price alert"],
        "icon": "command",
        "actions": ["open", "create-alert"],
        "is_command": True,
        "boost": 0.15,
    },
    {
        "id": "cmd-ask-ai",
        "title": "Ask AI",
        "subtitle": "Open AI Chat command center",
        "category": "commands",
        "kind": "command",
        "href": "/ai-chat",
        "keywords": ["ask ai", "chat"],
        "icon": "command",
        "actions": ["open"],
        "is_command": True,
        "boost": 0.2,
    },
]


def score_item(query: str, item: dict[str, Any]) -> float:
    q = query.strip().lower()
    if not q:
        return float(item.get("boost", 0))
    haystacks = [
        item.get("title", ""),
        item.get("subtitle") or "",
        item.get("symbol") or "",
        " ".join(item.get("keywords") or []),
        item.get("category", ""),
        item.get("kind", ""),
    ]
    blob = " ".join(haystacks).lower()
    score = float(item.get("boost", 0))
    if q == (item.get("title") or "").lower():
        score += 5
    elif q in blob:
        score += 2
    for token in q.split():
        if token and token in blob:
            score += 0.5
    return score
